# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_html_content": "00_scrapper.ipynb",
         "filter_tags": "00_scrapper.ipynb",
         "get_text_content": "00_scrapper.ipynb",
         "get_linked_urls": "00_scrapper.ipynb",
         "parse_webpage": "00_scrapper.ipynb"}

modules = ["scrapper.py"]

doc_url = "https://Vignesh-Nswamy.github.io/search_engine/"

git_url = "https://github.com/Vignesh-Nswamy/search_engine/tree/master/"

def custom_doc_links(name): return None
