# AUTOGENERATED! DO NOT EDIT! File to edit: 04_vectorizer.ipynb (unless otherwise specified).

__all__ = ['compute_tfidf']

# Cell
#export
from sklearn.feature_extraction.text import TfidfVectorizer

# Cell
#export
def compute_tfidf(documents):
    """
    Creats a vectorizer using all documents passed as a pandas series
    and computs tf-idf vectors for all documents.
    Returns the vectorizer and sparse vectors respresenting tf-idf of passed documents
    """
    vectorizer = TfidfVectorizer(use_idf=True)
    doc_tfidfs = vectorizer.fit_transform(documents)
    return vectorizer, doc_tfidfs